# Pre-commit hooks configuration
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

repos:
  # General pre-commit hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
        exclude: ^(data/|archive/|backups/|test-reports/|monitoring/|docs/|mem0/embedchain/)
      - id: end-of-file-fixer
        exclude: ^(data/|archive/|backups/|test-reports/|monitoring/|docs/|mem0/embedchain/)
      - id: check-yaml
        exclude: ^(data/|archive/|backups/|test-reports/|monitoring/|docs/|mem0/embedchain/|\.bmad-.*)
      - id: check-json
        exclude: ^(data/|archive/|backups/|test-reports/|monitoring/|docs/|mem0/embedchain/)
      - id: check-toml
        exclude: ^(data/|archive/|backups/|test-reports/|monitoring/|docs/|mem0/embedchain/)
      - id: check-added-large-files
        args: ['--maxkb=1000']
      - id: check-merge-conflict
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: mixed-line-ending
        args: ['--fix=lf']
      - id: pretty-format-json
        args: ['--autofix', '--indent=2']
        exclude: ^(data/|archive/|backups/|test-reports/|monitoring/|docs/|mem0/embedchain/)

  # Python formatting and linting
  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
        exclude: ^(data/|archive/|backups/|test-reports/|monitoring/|docs/|mem0/embedchain/)

  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        name: isort (python)
        args: ['--profile', 'black']
        exclude: ^(data/|archive/|backups/|test-reports/|monitoring/|docs/|mem0/embedchain/)

  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        exclude: ^(data/|archive/|backups/|test-reports/|monitoring/|docs/|mem0/|shared/|scripts/|tests/|openmemory/|test_memory_system\.py|quick_test_timezone\.py|run_timezone_tests\.py|validate_bmad_services\.py)
        additional_dependencies: [flake8-docstrings, flake8-typing-imports]

  # Security checks (disabled for now - focus on formatting first)
  # - repo: https://github.com/PyCQA/bandit
  #   rev: 1.7.8
  #   hooks:
  #     - id: bandit
  #       args: ["-r", ".", "-f", "json", "-o", "bandit-report.json"]
  #       exclude: ^(data/|archive/|backups/|test-reports/|monitoring/|docs/|mem0/embedchain/|tests/)

  # Type checking (disabled for now - focus on formatting first)
  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: v1.10.0
  #   hooks:
  #     - id: mypy
  #       exclude: ^(data/|archive/|backups/|test-reports/|monitoring/|docs/|mem0/embedchain/)
  #       additional_dependencies: [types-requests, types-PyYAML]

  # Documentation (disabled for now - too many issues to fix)
  # - repo: https://github.com/pycqa/pydocstyle
  #   rev: 6.3.0
  #   hooks:
  #     - id: pydocstyle
  #       exclude: ^(data/|archive/|backups/|test-reports/|monitoring/|docs/|mem0/embedchain/|tests/)

  # YAML formatting
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        types_or: [yaml]
        exclude: ^(data/|archive/|backups/|test-reports/|monitoring/|docs/|mem0/embedchain/|\.bmad-.*)

  # Shell script linting
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.10.0.1
    hooks:
      - id: shellcheck
        exclude: ^(data/|archive/|backups/|test-reports/|monitoring/|docs/|mem0/embedchain/|scripts/|openmemory/|health_check_memory\.sh|run_migrations\.sh|validate_bmad_services\.sh)

  # Dockerfile linting (temporarily disabled)
  # - repo: https://github.com/hadolint/hadolint
  #   rev: v2.12.0
  #   hooks:
  #     - id: hadolint
  #       exclude: ^(data/|archive/|backups/|test-reports/|monitoring/|docs/|mem0/embedchain/)

# Global configuration
default_language_version:
  python: python3

# Fail fast - stop on first failure
fail_fast: true

# Minimum pre-commit version
minimum_pre_commit_version: 3.0.0
