services:
  mem0:
    build:
      context: ./mem0
      dockerfile: server/dev.Dockerfile
    container_name: mem0
    restart: unless-stopped
    env_file: .env
    environment:
      # Database Configuration
      - DATABASE_HOST=${DATABASE_HOST:-postgres-mem0}
      - DATABASE_PORT=${DATABASE_PORT:-5432}
      - DATABASE_NAME=${DATABASE_NAME:-mem0}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_URL=${DATABASE_URL}
      # Neo4j Configuration
      - NEO4J_HOST=${NEO4J_HOST:-neo4j-mem0}
      - NEO4J_PORT=${NEO4J_PORT:-7687}
      - NEO4J_USERNAME=${NEO4J_USERNAME:-neo4j}
      - NEO4J_PASSWORD=${NEO4J_PASSWORD}
      - NEO4J_URI=${NEO4J_URI}
      - NEO4J_URL=${NEO4J_URL}
      # OpenAI Configuration
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_MODEL=${OPENAI_MODEL:-gpt-4o-mini}
      - OPENAI_EMBEDDING_MODEL=${OPENAI_EMBEDDING_MODEL:-text-embedding-3-small}
      # Application Configuration
      - APP_USER_ID=${APP_USER_ID}
      - APP_ENVIRONMENT=${APP_ENVIRONMENT:-development}
      - APP_DEBUG=${APP_DEBUG:-true}
      - APP_LOG_LEVEL=${APP_LOG_LEVEL:-INFO}
      # Legacy Variables (for backward compatibility)
      - POSTGRES_HOST=${DATABASE_HOST:-postgres-mem0}
      - POSTGRES_DB=${DATABASE_NAME:-mem0}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_COLLECTION_NAME=memories
      - USER=${APP_USER_ID}
    volumes:
      - ./data/mem0/history:/app/history
    ports:
      - '127.0.0.1:${MEM0_API_PORT:-8000}:8000'
    depends_on:
      postgres:
        condition: service_healthy
      neo4j:
        condition: service_healthy
    networks: [traefik]
    labels:
      - 'traefik.enable=true'
      - 'traefik.docker.network=traefik'
      - 'traefik.http.routers.mem0-oma.rule=Host(`mem0.drjlabs.com`)'
      - 'traefik.http.routers.mem0-oma.entrypoints=websecure'
      - 'traefik.http.routers.mem0-oma.tls=true'
      - 'traefik.http.services.mem0-oma.loadbalancer.server.port=8000'
    deploy:
      resources:
        limits:
          cpus: '4.0'
          memory: 4GB

  postgres:
    image: pgvector/pgvector:pg16
    container_name: postgres-mem0
    restart: unless-stopped
    environment:
      # Use standardized variables
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME:-mem0}
      - POSTGRES_HOST=${DATABASE_HOST:-postgres-mem0}
      - POSTGRES_PORT=${DATABASE_PORT:-5432}
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    command: >
      postgres -c 'shared_buffers=2GB' -c 'work_mem=256MB' -c 'maintenance_work_mem=1GB'
      -c 'effective_cache_size=6GB' -c 'max_connections=100' -c 'checkpoint_completion_target=0.9'
      -c 'random_page_cost=1.1' -c 'seq_page_cost=1' -c 'max_wal_size=4GB'
      -c 'min_wal_size=1GB' -c 'wal_buffers=64MB' -c 'default_statistics_target=100'
    networks: [traefik]
    healthcheck:
      test:
        [
          'CMD-SHELL',
          'pg_isready -q -d "$${DATABASE_NAME:-mem0}" -U "$${DATABASE_USER}"',
        ]
      interval: 5s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: '4.0'
          memory: 8GB
        reservations:
          cpus: '2.0'
          memory: 4GB

  neo4j:
    image: neo4j:5.26.4
    container_name: neo4j-mem0
    restart: unless-stopped
    environment:
      # Use standardized variables
      - NEO4J_AUTH=${NEO4J_AUTH}
      - NEO4J_PLUGINS=["apoc"]
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
      - NEO4J_server_memory_heap_initial__size=1G
      - NEO4J_server_memory_heap_max__size=4G
      - NEO4J_server_memory_pagecache_size=2G
    volumes:
      - ./data/neo4j:/data
    networks: [traefik]
    healthcheck:
      test: ['CMD-SHELL', 'wget -O /dev/null http://localhost:7474/ || exit 1']
      interval: 5s
      timeout: 5s
      retries: 5
    labels:
      - 'traefik.enable=true'
      - 'traefik.docker.network=traefik'
      - 'traefik.http.routers.neo4j-oma.rule=Host(`neo4j.drjlabs.com`)'
      - 'traefik.http.routers.neo4j-oma.entrypoints=websecure'
      - 'traefik.http.routers.neo4j-oma.tls=true'
      - 'traefik.http.services.neo4j-oma.loadbalancer.server.port=7474'
    deploy:
      resources:
        limits:
          cpus: '4.0'
          memory: 8GB
        reservations:
          cpus: '2.0'
          memory: 4GB

  # Host-based MCP Bridge Service (Linux approach)
  gpt-actions-bridge:
    build:
      context: ./gpt-actions-bridge
      dockerfile: Dockerfile
    container_name: gpt-actions-bridge
    restart: unless-stopped
    ports:
      - '127.0.0.1:8081:8080'
    networks: [traefik]
    env_file: .env
    environment:
      # API Keys (generate securely in production)
      - GPT_API_KEYS=${GPT_API_KEYS}
      # Backend service URLs (using Docker internal networking)
      - MEM0_API_BASE=http://mem0:8000
      - OPENMEMORY_API_BASE=http://openmemory-mcp:8765
    depends_on:
      - mem0
      - openmemory-mcp
      - postgres
      - neo4j
    labels:
      - 'traefik.enable=true'
      - 'traefik.docker.network=traefik'
      - 'traefik.http.routers.gpt-bridge.rule=Host(`mem-mcp.onemainarmy.com`)'
      - 'traefik.http.routers.gpt-bridge.entrypoints=websecure'
      - 'traefik.http.routers.gpt-bridge.tls=true'
      - 'traefik.http.services.gpt-bridge.loadbalancer.server.port=8080'
      - 'traefik.http.middlewares.gpt-ratelimit.ratelimit.burst=150'
      - 'traefik.http.middlewares.gpt-ratelimit.ratelimit.average=300'
      - 'traefik.http.routers.gpt-bridge.middlewares=gpt-ratelimit'
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:8080/health']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # OpenMemory Services
  openmemory-mcp:
    image: mem0/openmemory-mcp
    build:
      context: .
      dockerfile: ./openmemory/api/Dockerfile
    container_name: openmemory-mcp
    restart: unless-stopped
    environment:
      # Database Configuration
      - DATABASE_HOST=${DATABASE_HOST:-postgres-mem0}
      - DATABASE_PORT=${DATABASE_PORT:-5432}
      - DATABASE_NAME=${DATABASE_NAME:-mem0}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_URL=${DATABASE_URL}
      # Neo4j Configuration
      - NEO4J_HOST=${NEO4J_HOST:-neo4j-mem0}
      - NEO4J_PORT=${NEO4J_PORT:-7687}
      - NEO4J_USERNAME=${NEO4J_USERNAME:-neo4j}
      - NEO4J_PASSWORD=${NEO4J_PASSWORD}
      - NEO4J_URI=${NEO4J_URI}
      - NEO4J_URL=${NEO4J_URL}
      - NEO4J_AUTH=${NEO4J_AUTH}
      # OpenAI Configuration
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_MODEL=${OPENAI_MODEL:-gpt-4o-mini}
      - OPENAI_EMBEDDING_MODEL=${OPENAI_EMBEDDING_MODEL:-text-embedding-3-small}
      # Application Configuration
      - APP_USER_ID=${APP_USER_ID}
      - APP_ENVIRONMENT=${APP_ENVIRONMENT:-development}
      - APP_DEBUG=${APP_DEBUG:-true}
      - APP_LOG_LEVEL=${APP_LOG_LEVEL:-INFO}
      # API Configuration
      - API_PORT=${OPENMEMORY_API_PORT:-8765}
      - API_WORKERS=${API_WORKERS:-4}
      - API_TIMEOUT=${API_TIMEOUT:-30}
      # OIDC Authentication Configuration
      - OIDC_JWKS_URL=${OIDC_JWKS_URL:-https://oidc.drjlabs.com/auth/jwks}
      - OIDC_ISSUER=${OIDC_ISSUER:-https://oidc.drjlabs.com}
      - OIDC_AUDIENCE=${OIDC_AUDIENCE}
      # Legacy Variables (for backward compatibility)
      - USER=${APP_USER_ID}
      - API_KEY=${OPENAI_API_KEY}
      - POSTGRES_HOST=${DATABASE_HOST:-postgres-mem0}
      - POSTGRES_DB=${DATABASE_NAME:-mem0}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - PYTHONWARNINGS=ignore::DeprecationWarning
    env_file:
      - ./openmemory/api/.env
    ports:
      - '127.0.0.1:${OPENMEMORY_API_PORT:-8765}:8765'
    volumes:
      - ./openmemory/api:/usr/src/openmemory
    command: >
      sh -c "uvicorn main:app --host 0.0.0.0 --port 8765 --workers ${API_WORKERS:-4}"
    networks: [traefik]
    labels:
      - 'traefik.enable=true'
      - 'traefik.docker.network=traefik'
      - 'traefik.http.routers.openmemory-mcp.rule=Host(`mcp.drjlabs.com`)'
      - 'traefik.http.routers.openmemory-mcp.entrypoints=websecure'
      - 'traefik.http.routers.openmemory-mcp.tls=true'
      - 'traefik.http.services.openmemory-mcp.loadbalancer.server.port=8765'
    depends_on:
      postgres:
        condition: service_healthy
      neo4j:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 1GB
        reservations:
          cpus: '1.0'
          memory: 512MB

  openmemory-ui:
    build:
      context: ./openmemory/ui/
      dockerfile: Dockerfile
    image: mem0/openmemory-ui:latest
    container_name: openmemory-ui
    restart: unless-stopped
    environment:
      # Frontend Configuration
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL:-http://localhost:8765}
      - NEXT_PUBLIC_USER_ID=${NEXT_PUBLIC_USER_ID:-drj}
      - NEXT_PUBLIC_ENVIRONMENT=${NEXT_PUBLIC_ENVIRONMENT:-development}
      - NEXT_PUBLIC_BUILD_TIME=${NEXT_PUBLIC_BUILD_TIME:-auto_generated}
      - NEXT_PUBLIC_VERSION=${NEXT_PUBLIC_VERSION:-1.0.0}
      # Application Configuration
      - APP_USER_ID=${APP_USER_ID}
      - APP_ENVIRONMENT=${APP_ENVIRONMENT:-development}
      - APP_DEBUG=${APP_DEBUG:-true}
      - APP_LOG_LEVEL=${APP_LOG_LEVEL:-INFO}
      # Service Configuration
      - OPENMEMORY_API_URL=${OPENMEMORY_API_URL:-http://localhost:8765}
      - OPENMEMORY_UI_URL=${OPENMEMORY_UI_URL:-http://localhost:3000}
      - UI_PORT=${OPENMEMORY_UI_PORT:-3000}
      # Legacy Variables (for backward compatibility)
      - USER=${APP_USER_ID}
    env_file:
      - ./openmemory/ui/.env
    ports:
      - '127.0.0.1:${OPENMEMORY_UI_PORT:-3000}:3000'
    networks: [traefik]
    labels:
      - 'traefik.enable=true'
      - 'traefik.docker.network=traefik'
      - 'traefik.http.routers.openmemory-ui.rule=Host(`memory.drjlabs.com`)'
      - 'traefik.http.routers.openmemory-ui.entrypoints=websecure'
      - 'traefik.http.routers.openmemory-ui.tls=true'
      - 'traefik.http.services.openmemory-ui.loadbalancer.server.port=3000'
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512MB
        reservations:
          cpus: '0.5'
          memory: 256MB

  # OIDC Authentication Server for ChatGPT Integration
  oidc-auth-server:
    build:
      context: ./oidc-auth-server
      dockerfile: Dockerfile
    container_name: oidc-auth-server
    restart: unless-stopped
    environment:
      # Google OAuth Configuration
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GOOGLE_REDIRECT_URI=${GOOGLE_REDIRECT_URI:-https://oidc.drjlabs.com/auth/callback}
      # OIDC Server Configuration
      - OIDC_BASE_URL=${OIDC_BASE_URL:-https://oidc.drjlabs.com}
      - OIDC_JWKS_URL=${OIDC_JWKS_URL:-https://oidc.drjlabs.com/auth/jwks}
      - RSA_PRIVATE_KEY_PEM=${RSA_PRIVATE_KEY_PEM}
      - JWT_KEY_ID=${JWT_KEY_ID:-key1}
      - ENVIRONMENT=${APP_ENVIRONMENT:-production}
    env_file:
      - ./oidc-auth-server/.env
    ports:
      - '127.0.0.1:${OIDC_PORT:-8766}:8766'
    networks: [traefik]
    labels:
      - 'traefik.enable=true'
      - 'traefik.docker.network=traefik'
      - 'traefik.http.routers.oidc-auth.rule=Host(`oidc.drjlabs.com`)'
      - 'traefik.http.routers.oidc-auth.entrypoints=websecure'
      - 'traefik.http.routers.oidc-auth.tls=true'
      - 'traefik.http.services.oidc-auth.loadbalancer.server.port=8766'
      # Security middleware
      - 'traefik.http.middlewares.oidc-ratelimit.ratelimit.burst=50'
      - 'traefik.http.middlewares.oidc-ratelimit.ratelimit.average=100'
      - 'traefik.http.routers.oidc-auth.middlewares=oidc-ratelimit'
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:8766/health']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256MB
        reservations:
          cpus: '0.25'
          memory: 128MB
    profiles: ["auth"]  # Optional profile for selective deployment

  # Redis for OIDC token storage (production)
  redis-oidc:
    image: redis:7-alpine
    container_name: redis-oidc
    restart: unless-stopped
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
    volumes:
      - ./data/redis:/data
    networks: [traefik]
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 5s
      retries: 3
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 256MB
        reservations:
          cpus: '0.125'
          memory: 128MB
    profiles: ["auth"]  # Optional profile for selective deployment

networks:
  traefik:
    external: true
