repos:
  - repo: local
    hooks:
      - id: ruff
        name: Ruff
        entry: python3 -m ruff check --fix
        language: system
        types: [python]

      - id: isort
        name: isort
        entry: python3 -m isort
        language: system
        types: [python]
        args: ['--profile', 'black']
