version: 2
updates:
  # Main Python package
  - package-ecosystem: 'pip'
    directory: '/mem0'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '06:00'
      timezone: 'America/New_York'
    open-pull-requests-limit: 5
    groups:
      python-deps:
        patterns:
          - '*'
    allow:
      - dependency-type: 'all'
    reviewers:
      - 'maintainers'
    labels:
      - 'dependencies'
      - 'python'
    target-branch: 'main'
    rebase-strategy: 'auto'

  # OpenMemory API Python package
  - package-ecosystem: 'pip'
    directory: '/openmemory/api'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '06:00'
      timezone: 'America/New_York'
    open-pull-requests-limit: 5
    groups:
      python-deps:
        patterns:
          - '*'
    allow:
      - dependency-type: 'all'
    reviewers:
      - 'maintainers'
    labels:
      - 'dependencies'
      - 'python'
    target-branch: 'main'
    rebase-strategy: 'auto'

  # Server Python package
  - package-ecosystem: 'pip'
    directory: '/mem0/server'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '06:00'
      timezone: 'America/New_York'
    open-pull-requests-limit: 5
    groups:
      python-deps:
        patterns:
          - '*'
    allow:
      - dependency-type: 'all'
    reviewers:
      - 'maintainers'
    labels:
      - 'dependencies'
      - 'python'
      - 'server'
    target-branch: 'main'
    rebase-strategy: 'auto'

  # Main TypeScript package
  - package-ecosystem: 'npm'
    directory: '/mem0/mem0-ts'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '06:00'
      timezone: 'America/New_York'
    open-pull-requests-limit: 5
    groups:
      npm-deps:
        patterns:
          - '*'
    allow:
      - dependency-type: 'all'
    reviewers:
      - 'maintainers'
    labels:
      - 'dependencies'
      - 'typescript'
    target-branch: 'main'
    rebase-strategy: 'auto'

  # Vercel AI SDK TypeScript package
  - package-ecosystem: 'npm'
    directory: '/mem0/vercel-ai-sdk'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '06:00'
      timezone: 'America/New_York'
    open-pull-requests-limit: 5
    groups:
      npm-deps:
        patterns:
          - '*'
    allow:
      - dependency-type: 'all'
    reviewers:
      - 'maintainers'
    labels:
      - 'dependencies'
      - 'typescript'
      - 'vercel-ai-sdk'
    target-branch: 'main'
    rebase-strategy: 'auto'

  # OpenMemory UI TypeScript package
  - package-ecosystem: 'npm'
    directory: '/openmemory/ui'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '06:00'
      timezone: 'America/New_York'
    open-pull-requests-limit: 5
    groups:
      npm-deps:
        patterns:
          - '*'
    allow:
      - dependency-type: 'all'
    reviewers:
      - 'maintainers'
    labels:
      - 'dependencies'
      - 'typescript'
      - 'openmemory'
    target-branch: 'main'
    rebase-strategy: 'auto'

  # GitHub Actions
  - package-ecosystem: 'github-actions'
    directory: '/mem0/.github/workflows'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '06:00'
      timezone: 'America/New_York'
    open-pull-requests-limit: 3
    groups:
      actions-deps:
        patterns:
          - '*'
    allow:
      - dependency-type: 'all'
    reviewers:
      - 'maintainers'
    labels:
      - 'dependencies'
      - 'github-actions'
    target-branch: 'main'
    rebase-strategy: 'auto'

  # Root level dependencies (Python)
  - package-ecosystem: 'pip'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '06:00'
      timezone: 'America/New_York'
    open-pull-requests-limit: 5
    groups:
      python-deps:
        patterns:
          - '*'
    allow:
      - dependency-type: 'all'
    reviewers:
      - 'maintainers'
    labels:
      - 'dependencies'
      - 'python'
      - 'root'
    target-branch: 'main'
    rebase-strategy: 'auto'

  # Root level dependencies (npm)
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '06:00'
      timezone: 'America/New_York'
    open-pull-requests-limit: 5
    groups:
      npm-deps:
        patterns:
          - '*'
    allow:
      - dependency-type: 'all'
    reviewers:
      - 'maintainers'
    labels:
      - 'dependencies'
      - 'typescript'
      - 'root'
    target-branch: 'main'
    rebase-strategy: 'auto'
