version: 2
updates:
  # Main Python package
  - package-ecosystem: 'pip'
    directory: '/mem0'
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 5
    allow:
      - dependency-type: 'all'
    reviewers:
      - 'maintainers'
    labels:
      - 'dependencies'
      - 'python'
    # Security-focused enhancements
    target-branch: 'main'
    rebase-strategy: 'auto'

  # Embedchain Python package - REMOVED (legacy, not maintained)

  # OpenMemory API Python package
  - package-ecosystem: 'pip'
    directory: '/openmemory/api'
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 5
    allow:
      - dependency-type: 'all'
    reviewers:
      - 'maintainers'
    labels:
      - 'dependencies'
      - 'python'
      - 'openmemory'
    # Security-focused enhancements
    target-branch: 'main'
    rebase-strategy: 'auto'

  # Server Python package
  - package-ecosystem: 'pip'
    directory: '/mem0/server'
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 5
    allow:
      - dependency-type: 'all'
    reviewers:
      - 'maintainers'
    labels:
      - 'dependencies'
      - 'python'
      - 'server'
    # Security-focused enhancements
    target-branch: 'main'
    rebase-strategy: 'auto'

  # Main TypeScript package
  - package-ecosystem: 'npm'
    directory: '/mem0/mem0-ts'
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 5
    allow:
      - dependency-type: 'all'
    reviewers:
      - 'maintainers'
    labels:
      - 'dependencies'
      - 'typescript'
    # Security-focused enhancements
    target-branch: 'main'
    rebase-strategy: 'auto'

  # Vercel AI SDK TypeScript package
  - package-ecosystem: 'npm'
    directory: '/mem0/vercel-ai-sdk'
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 5
    allow:
      - dependency-type: 'all'
    reviewers:
      - 'maintainers'
    labels:
      - 'dependencies'
      - 'typescript'
      - 'vercel-ai-sdk'
    # Security-focused enhancements
    target-branch: 'main'
    rebase-strategy: 'auto'

  # OpenMemory UI TypeScript package
  - package-ecosystem: 'npm'
    directory: '/openmemory/ui'
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 5
    allow:
      - dependency-type: 'all'
    reviewers:
      - 'maintainers'
    labels:
      - 'dependencies'
      - 'typescript'
      - 'openmemory'
    # Security-focused enhancements
    target-branch: 'main'
    rebase-strategy: 'auto'

  # Community TypeScript package - REMOVED (not actively maintained)

  # Example projects - REMOVED (not maintained)

  # GitHub Actions
  - package-ecosystem: 'github-actions'
    directory: '/mem0/.github/workflows'
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 3
    reviewers:
      - 'maintainers'
    labels:
      - 'dependencies'
      - 'github-actions'
    # Security-focused enhancements
    target-branch: 'main'
    rebase-strategy: 'auto'

  # Root level dependencies
  - package-ecosystem: 'pip'
    directory: '/'
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 5
    allow:
      - dependency-type: 'all'
    reviewers:
      - 'maintainers'
    labels:
      - 'dependencies'
      - 'python'
      - 'root'
    # Security-focused enhancements
    target-branch: 'main'
    rebase-strategy: 'auto'

  # OpenMemory root UI dependencies
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 5
    allow:
      - dependency-type: 'all'
    reviewers:
      - 'maintainers'
    labels:
      - 'dependencies'
      - 'typescript'
      - 'root'
    # Security-focused enhancements
    target-branch: 'main'
    rebase-strategy: 'auto'
