version: 2
updates:
  # Main Python package
  - package-ecosystem: "pip"
    directory: "/mem0"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    allow:
      - dependency-type: "all"
    reviewers:
      - "maintainers"
    labels:
      - "dependencies"
      - "python"

  # Embedchain Python package
  - package-ecosystem: "pip"
    directory: "/mem0/embedchain"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    allow:
      - dependency-type: "all"
    reviewers:
      - "maintainers"
    labels:
      - "dependencies"
      - "python"
      - "embedchain"

  # OpenMemory API Python package
  - package-ecosystem: "pip"
    directory: "/mem0/openmemory/api"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    allow:
      - dependency-type: "all"
    reviewers:
      - "maintainers"
    labels:
      - "dependencies"
      - "python"
      - "openmemory"

  # Server Python package
  - package-ecosystem: "pip"
    directory: "/mem0/server"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    allow:
      - dependency-type: "all"
    reviewers:
      - "maintainers"
    labels:
      - "dependencies"
      - "python"
      - "server"

  # Main TypeScript package
  - package-ecosystem: "npm"
    directory: "/mem0/mem0-ts"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    allow:
      - dependency-type: "all"
    reviewers:
      - "maintainers"
    labels:
      - "dependencies"
      - "typescript"

  # Vercel AI SDK TypeScript package
  - package-ecosystem: "npm"
    directory: "/mem0/vercel-ai-sdk"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    allow:
      - dependency-type: "all"
    reviewers:
      - "maintainers"
    labels:
      - "dependencies"
      - "typescript"
      - "vercel-ai-sdk"

  # OpenMemory UI TypeScript package
  - package-ecosystem: "npm"
    directory: "/mem0/openmemory/ui"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    allow:
      - dependency-type: "all"
    reviewers:
      - "maintainers"
    labels:
      - "dependencies"
      - "typescript"
      - "openmemory"

  # Community TypeScript package
  - package-ecosystem: "npm"
    directory: "/mem0/mem0-ts/src/community"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    allow:
      - dependency-type: "all"
    reviewers:
      - "maintainers"
    labels:
      - "dependencies"
      - "typescript"
      - "community"

  # Example projects
  - package-ecosystem: "npm"
    directory: "/mem0/examples/mem0-demo"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3
    allow:
      - dependency-type: "all"
    reviewers:
      - "maintainers"
    labels:
      - "dependencies"
      - "examples"

  - package-ecosystem: "npm"
    directory: "/mem0/examples/multimodal-demo"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3
    allow:
      - dependency-type: "all"
    reviewers:
      - "maintainers"
    labels:
      - "dependencies"
      - "examples"

  - package-ecosystem: "npm"
    directory: "/mem0/examples/vercel-ai-sdk-chat-app"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3
    allow:
      - dependency-type: "all"
    reviewers:
      - "maintainers"
    labels:
      - "dependencies"
      - "examples"

  - package-ecosystem: "npm"
    directory: "/mem0/examples/openai-inbuilt-tools"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3
    allow:
      - dependency-type: "all"
    reviewers:
      - "maintainers"
    labels:
      - "dependencies"
      - "examples"

  - package-ecosystem: "npm"
    directory: "/mem0/examples/yt-assistant-chrome"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3
    allow:
      - dependency-type: "all"
    reviewers:
      - "maintainers"
    labels:
      - "dependencies"
      - "examples"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/mem0/.github/workflows"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3
    reviewers:
      - "maintainers"
    labels:
      - "dependencies"
      - "github-actions" 